# Generated by Django 2.1.1 on 2018-09-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nome')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço unitário')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='data')),
                ('number', models.IntegerField(verbose_name='número')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço unitário')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sale')),
            ],
        ),
    ]
